name: Get logs
on:
  workflow_dispatch:
    inputs:
      since:
        description: 'Show logs since'
        default: ''
        type: string
jobs:
  get_logs:
    name: Get the logs of teh wk-app.service
    runs-on: ubuntu-latest
    steps:
    - name: Get the logs of teh wk-app.service
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.OVH_DEBIAN_HOST }}
        username: ${{ secrets.OVH_DEBIAN_USERNAME }}
        password: ${{ secrets.OVH_DEBIAN_PASSWORD }}
        port: ${{ secrets.OVH_DEBIAN_PORT }}
        debug: true
        script: |
          echo ${{ inputs.since }}
          sudo journalctl -u wk-app.service --no-tail
