name: remote ssh command test
on: workflow_dispatch
jobs:
  who_am_i:
    name: Who am I test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.OVH_DEBIAN_HOST }}
        username: ${{ secrets.OVH_DEBIAN_USERNAME }}
        password: ${{ secrets.OVH_DEBIAN_PASSWORD }}
        port: ${{ secrets.OVH_DEBIAN_PORT }}
        debug: true
        script: |
          whoami
          ls -al
